# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Check Maven java-version
      run: mvn -v
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        # Set CC_TEST_REPORTER_ID as secret of your repo
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
        coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco


